---
title: "Timilsina et al Supplementary figures"
author: "Nourhan Abdelfattah"
date: "2024-11-8"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r directories, include=FALSE}
PathwayOutputFolder="~/Library/CloudStorage/Box-Box/SantoshProject/Output_Sep26/AllClusters/PathwayAnalysisbySampleperAssignment/"
CellChatRobjDirectory = "~/Library/CloudStorage/Box-Box/SantoshProject/Output_Sep26/Cellchat/CellChatObjects/"
OutputDirectory="~/Library/CloudStorage/Box-Box/SantoshProject/ManuscriptFigs/"
dir.create(OutputDirectory)
RobjDirectory="~/Library/CloudStorage/Box-Box/SantoshProject/R_Objects/"
infercnv_obj = readRDS("~/Library/CloudStorage/Box-Box/SantoshProject/infCNVAug3124 Allcells/run.final.infercnv_obj")
mapmeta=read.delim(file = paste0("~/Library/CloudStorage/Box-Box/SantoshProject/infCNVAug3124 Allcells/map_metadata_from_infercnv.txt"))
marker.list=list(Anti_Apoptosis = c("Bcl11b", "Bcl2l1", "Bag3", "Bag4", "Birc3", 
"Gadd45b"), `B1 B` = c("Ms4a1", "Sspn", "Itgb1", "Epha4", "Col4a4", 
"Prdm1", "Irf4", "Cd38", "Xbp1", "Pax5", "Bcl11a", "Blk"), Basophil = c("Itga2", 
"Cd9", "Clec12a"), CAFs = c("Dcn", "Col1a1", "Lum", "Col1a2", 
"Sfrp2", "Col3a1", "Apod", "Postn", "Cthrc1", "Mmp11", "Col6a3", 
"Ccn2", "Ctsk", "C1s1", "Col6a2", "Fn1", "Ccdc80", "Sparc", "Rarres2", 
"Cxcl14", "Col6a1", "Sfrp4", "Aebp1", "Bgn", "Ptgds", "Serpinf1", 
"Mmp2", "Cfd", "Timp1", "Fbln1", "Vcan", "C1ra", "C3", "Mfap4", 
"Cxcl12", "Ccn1", "Col5a2", "Mxra8", "Islr", "Igfbp4", "Gsn", 
"Serping1", "Igf2", "Igf1", "Pcolce", "Meg3", "Spon2", "Thy1", 
"Cald1", "Igfbp6", "Mfap2", "Aspn", "Lgals1", "Dpt", "Timp3", 
"Thbs2", "Fstl1", "Nnmt", "Lrp1", "Col5a1", "Htra1", "Col14a1", 
"Col12a1", "Timp2", "Fbln2", "Srpx", "Pdgfrl", "Olfml3", "Efemp1", 
"Mmp14", "Laptm4a", "Gem", "Ppic", "Igfbp7", "Egr1", "Fbn1", 
"Cd63", "Prrx1", "Pmp22", "Htra3", "Tmem176b", "Tnfaip6", "Mdk", 
"Cdh11", "Comp", "Clec11a", "Col10a1", "Fgf7", "Palld", "Efemp2", 
"Mfap5", "Fbln5", "Cyp1b1", "Serpinh1", "Lgals3bp", "Col8a1", 
"Plpp3", "Cfh", "Cilp", "Fap", "Rcn3", "Podn", "Nbl1", "Prss23", 
"Eln", "Sulf1", "Tmem176a", "Id3", "Lhfp", "Col11a1", "Cst3", 
"Crispld2", "F2r", "Ifitm3", "Gpnmb", "Adam12", "Tcf4", "Sod3", 
"Ggt5"), `CD14+ Mono` = c("Fcna", "Cd14", "S100a8", "S100a9"), 
    `CD16+ Mono` = c("Tcf7l2", "Fcgr3", "Lyn", "Lst1", "Hk3"), 
    `CD4+ T activated` = c("Cd4", "Il7r", "Trbc2", "Itgb1"), 
    `CD4+ T Naïve` = c("Cd4", "Il7r", "Trbc2", "Ccr7"), `CD8+ T` = c("Cd8a", 
    "Cd8b1", "Gzmk", "Gzma", "Ccl5", "Gzmb", "Gzmc", "Gzma"), 
    cDC1 = c("Clec9a", "Cadm1", "Cpne3", "Dnase1l3", "Wdfy4"), 
    cDC2 = c("Ccr7", "Fscn1", "Lamp3", "Marcksl1"), cDC3 = c("Clec10a", 
    "Fcer1a", "Ppa1"), `E0771 markers` = c("Pcm1", "Map1b", "Hspg2", 
    "Serpine1", "Scd2", "Nrp2", "Nedd4", "Tead1", "Eprs", "Hspa9", 
    "Myc", "Ubr4", "Prrc2a", "Flnb", "Tcf20"), Endothelial = c("Ackr1", 
    "Fabp4", "Plvap", "Ramp2", "Vwf", "Aqp1", "Cldn5", "Sparcl1", 
    "Gng11", "Pecam1", "Eng", "Egfl7", "Hspg2", "Ramp3", "A2m", 
    "Spry1", "Clec14a", "Rbp7", "Emcn", "Igfbp7", "Adgrl4", "Id1", 
    "Npdc1", "Esam", "Calcrl", "Cav1", "Igfbp3", "Ifi27", "Rnase1", 
    "Cd34", "Cavin2", "Ifitm3", "Igfbp4", "Fkbp1a", "Tm4sf1", 
    "Plpp1", "Hyal2", "Slc9a3r2", "Crip2", "Pdlim1", "Col15a1", 
    "Col4a1", "Epas1", "Prcp", "Palmd", "Emp1", "Cd36", "Cd93", 
    "Tcf4", "Socs3", "Cavin1", "Col4a2", "Flt1", "Pdk4", "Cyyr1", 
    "Id3", "Bcam", "Mctp1", "Lmcd1", "Adamts1", "Sele", "Adamts9", 
    "Tgfbr2", "Cd59a", "Rcan1", "Edn1", "Tspan7", "Stc1", "Il33", 
    "Icam2", "Ets2", "Arhgap29", "Gsn", "Cdh5", "Podxl", "Ptprb", 
    "Mgll", "Sptbn1", "Mmrn2", "Stom", "Adam15", "Jam2", "Sox17", 
    "Mgst2", "S1pr1", "Thbd", "Vwa1", "Nnmt", "Vim", "Sparc", 
    "Clu", "App", "Dusp23", "Itga6", "Heg1", "Adcy4", "Nrn1", 
    "Ldb2", "Fabp5", "Mall", "Nrp1"), Erythroblast = c("Mki67", 
    "Hba-a1", "Hba-a2"), `Fatty acid metabolism` = c("Acaa1a", 
    "Acadm", "Acadvl", "Acsl5", "Aldh16a1", "Aldh9a1", "Ech1", 
    "Echs1", "Hadha", "Hsd17b10", "Slc27a2", "Decr1", "Pex16", 
    "Scp2"), Fibroblasts = c("Fbln1", "Dcn", "Lum", "C1s1", "C1ra", 
    "Slit2", "Col1a1", "Col1a2", "Col3a1", "Col6a3", "Aspn", 
    "Ltbp1", "Itgbl1", "Cald1", "Postn", "Bgn", "Sfrp2"), `G/M prog` = c("Mpo", 
    "Bcl2", "Kcnq5", "Csf3r"), Glycolysis = c("Slc2a3", "Slc2a8", 
    "Pfkfb3", "Aldoa", "Eno1", "Gapdh", "Gpi1", "Pgam1", "Pgk1", 
    "Pkm", "Tpi1", "Gyg", "Mdh1", "Mdh2", "Ldha", "Ldhb", "Adh5", 
    "Idh2"), Hypoxia = c("Ackr3", "Adm", "Adora2b", "Ak4", "Akap12", 
    "Aldoa", "Aldob", "Aldoc", "Ampd3", "Angptl4", "Ankzf1", 
    "Anxa2", "Atf3", "Atp7a", "B3galt6", "B4galnt2", "Bcan", 
    "Bcl2", "Bgn", "Bhlhe40", "Bnip3l", "Brs3", "Btg1", "Car12", 
    "Casp6", "Cav1", "Cavin1", "Cavin3", "Ccn1", "Ccn2", "Ccn5", 
    "Ccng2", "Cdkn1a", "Cdkn1b", "Cdkn1c", "Cdkn1c", "Chst2", 
    "Chst3", "Cited2", "Col5a1", "Cp", "Csrp2", "Cxcr4", "Dcn", 
    "Ddit3", "Ddit4", "Dpysl4", "Dtna", "Dusp1", "Edn2", "Efna1", 
    "Efna3", "Egfr", "Eno1", "Eno2", "Eno3", "Errfi1", "Ets1", 
    "Ext1", "F3", "Fam162a", "Fbp1", "Fos", "Fosl2", "Foxo3", 
    "Gaa", "Galk1", "Gapdh", "Gapdhs", "Gbe1", "Gck", "Gcnt2", 
    "Gcnt2", "Glrx", "Gpc1", "Gpc3", "Gpc4", "Gpi1", "Grhpr", 
    "Gys1", "Has1", "Hdlbp", "Hexa", "Hk1", "Hk2", "Hmox1", "Hoxb9", 
    "Hs3st1", "Hspa5", "Ids", "Ier3", "Ier3", "Ier3", "Ier3", 
    "Ier3", "Ier3", "Ier3", "Igfbp1", "Igfbp3", "Il6", "Ilvbl", 
    "Inha", "Irs2", "Isg20", "Jmjd6", "Jun", "Kdelr3", "Kdm3a", 
    "Kif5a", "Klf6", "Klf7", "Klhl24", "Lalba", "Large1", "Ldha", 
    "Ldha", "Ldhc", "Lox", "Lxn", "Maff", "Map3k1", "Mif", "Mif", 
    "Mxi1", "Myh9", "Nagk", "Ncan", "Ndrg1", "Ndst1", "Ndst2", 
    "Nedd4l", "Nfil3", "Noct", "Nr3c1", "P4ha1", "P4ha2", "Pam", 
    "Pck1", "Pdgfb", "Pdk1", "Pdk3", "Pfkfb3", "Pfkl", "Pfkp", 
    "Pgam2", "Pgf", "Pgk1", "Pgm1", "Pgm2", "Phkg1", "Pim1", 
    "Pklr", "Pklr", "Pkp1", "Plac8", "Plaur", "Plin2", "Pnrc1", 
    "Ppargc1a", "Ppfia4", "Ppp1r15a", "Ppp1r3c", "Prdx5", "Prkca", 
    "Pygm", "Rbpj", "Rora", "Rragd", "S100a4", "Sap30", "Scarb1", 
    "Sdc2", "Sdc3", "Sdc4", "Selenbp1", "Serpine1", "Siah2", 
    "Slc25a1", "Slc2a1", "Slc2a3", "Slc2a5", "Slc37a4", "Slc37a4", 
    "Slc37a4", "Slc6a6", "Srpx", "Stbd1", "Stc1", "Stc2", "Sult2b1", 
    "Tes", "Tgfb3", "Tgfbi", "Tgm2", "Tiparp", "Tktl1", "Tmem45a", 
    "Tnfaip3", "Tpbg", "Tpbg", "Tpd52", "Tpi1", "Tpst2", "Ugp2", 
    "Vegfa", "Vhl", "Vldlr", "Wsb1", "Xpnpep1", "Zfp36"), `ID2-hi myeloid prog` = c("Cd14", 
    "Id2", "Vcan", "S100a9", "Clec12a", "Klf4", "Plaur"), `Lymph prog` = c("Vpreb1", 
    "Mme", "Ebf1", "Ssbp2", "Bach2", "Cd79b", "Ighm", "Pax5", 
    "Prkce", "Dntt", "Igll1"), M2_Macs = c("Ms4a6d", "Cd163", 
    "Stab1", "Slc1a3", "Colec12", "F13a1", "Mrc1", "Tlr2", "Cd163l1", 
    "Slco2b1"), Macs = c("Spic", "Fabp3", "Cd5l", "Ccl3", "C1qc", 
    "C1qb", "Fabp4", "C1qa", "Apoe", "Selenop"), Mast = c("Kit", 
    "Tpsab1", "Cpa3", "Clu"), `MK/E prog` = c("Itga2b", "Ryr3"
    ), Naïve = c("Il7r", "Ccr7", "Sell", "Foxo1", "Klf2", "Klf3", 
    "Lef1", "Tcf7", "Actn1", "Foxp1"), `Naïve CD20+ B` = c("Ms4a1", 
    "Il4ra", "Ighd", "Fcrl1", "Ighm"), Neutrophils = c("Cxcl10", 
    "Ifit1", "Rsad2", "Stat1"), NK = c("Nkg7", "Cd247", "Grik4", 
    "Fcer1g", "Tyrobp", "Klrg1", "Fcgr3"), `Normal Epithelial` = c("Krt14", 
    "Krt17", "Ltf", "Krt15", "Ptn", "Mgp", "Tacstd2", "Mmp7", 
    "Scgb3a1", "Krt5", "Cryab", "Cxcl2", "Saa1", "Cldn4", "Wfdc2", 
    "Mylk", "Tm4sf1", "Sfrp1", "Azgp1", "Dst", "Krt8", "Csrp1", 
    "Actg2", "Krt7", "Tagln", "Clu", "Pdlim3", "Sfn", "Maff", 
    "Slpi", "Ccl28", "Fbxo32", "Perp", "Krt18", "Cnn1", "Cxcl14", 
    "Ccn1", "Rcan1", "Acta2", "Pip"), Normoblast = c("Slc4a1", 
    "Slc25a37", "Hba-a2", "Hba-a1", "Tfrc"), `Oxidative phosphorylation` = c("Atp6v1h", 
    "Atp2b4", "Atp6v1g3", "Atp1b1", "Atp1a4", "Atp1a2", "Atp5c1", 
    "Atp5g3", "Atp8b4", "Atp9a", "Atp5e", "Atp11b", "Atp8b2", 
    "Atp1a1", "Atp5f1", "Atp6v0d2", "Atp8b5", "Atp6v1g1", "Atpaf1", 
    "Atp6v0b", "Atpif1", "Atp13a2", "Atp8a1", "Atp5k", "Atp2a2", 
    "Atp6v0a2", "Atp5j2", "Atp6v1f", "Atp6v1fnb", "Atp6v0a4", 
    "Atp6v0e2", "Atp6v1b1", "Atp2b2", "Atp6v1e1", "Atp1a3", "Atp4a", 
    "Atp10a", "Atp2a1", "Atp11a", "Atp4b", "Atp7b", "Atp6v1b2", 
    "Atp13a1", "Atp6v0d1", "Atp2c2", "Atp5l", "Atp1b3", "Atp2c1", 
    "Atp5d", "Atp8b3", "Atp2b1", "Atp23", "Atp5b", "Atp10b", 
    "Atpaf2", "Atp1b2", "Atp2a3", "Atp5g1", "Atp6v0a1", "Atp5h", 
    "Atp6v1c2", "Atp6v1d", "Atp5mpl", "Atp6ap1l", "Atp12a", "Atp8a2", 
    "Atpsckmt", "Atp6v1c1", "Atp5g2", "Atp13a5", "Atp13a4", "Atp13a3", 
    "Atp6v1a", "Atp5j", "Atp5o", "Atp6v0c", "Atp6v0e", "Atp6v1g2", 
    "Atp6v1e2", "Atp8b1", "Atp5a1", "Atp9b", "Atp5md", "Atp6ap2", 
    "Atp1b4", "Atp11c", "Atp2b3", "Atp6ap1", "Atp7a", "Cox16", 
    "Cox17", "Cox4i1", "Cox5a", "Cox5b", "Cox6a1", "Cox6b1", 
    "Cox6c", "Cox7a2", "Cox7b", "Cox7c", "Cox8a", "Cyc1", "mt-Nd1", 
    "mt-Nd2", "mt-Co1", "mt-Co2", "mt-Atp8", "mt-Atp6", "mt-Co3", 
    "mt-Nd3", "mt-Nd4l", "mt-Nd4", "mt-Nd5", "mt-Nd6", "mt-Cytb", 
    "Ndufa1", "Ndufa10", "Ndufa11", "Ndufa12", "Ndufa13", "Ndufa2", 
    "Ndufa3", "Ndufa4", "Ndufa5", "Ndufa6", "Ndufab1", "Ndufaf3", 
    "Ndufaf4", "Ndufaf8", "Ndufb10", "Ndufb11", "Ndufb2", "Ndufb3", 
    "Ndufb4", "Ndufb6", "Ndufb7", "Ndufb8", "Ndufb9", "Ndufc1", 
    "Ndufc2", "Ndufs2", "Ndufs3", "Ndufs5", "Ndufs6", "Ndufs7", 
    "Ndufs8", "Ndufv1", "Ndufv2", "Sdha", "Sdhb", "Tcirg1", "Uqcrb", 
    "Uqcrc1", "Uqcrc2", "Uqcrfs1", "Uqcrh", "Uqcrq", "Surf1", 
    "Surf4"), pDCs = c("Siglech", "Ccr9", "Ly6d", "Jchain"), 
    `Plasma cells` = c("Mzb1", "Hsp90b1", "Fndc3b", "Prdm1", 
    "Igkc", "Jchain"), Plasmablast = c("Xbp1", "Prdm1"), Pro_Apoptosis = c("Bcl2l11", 
    "Bid", "Bin1", "Bin2", "Bax", "Bak1", "Casp8", "Casp3"), 
    PVL = c("Acta2", "Rgs5", "Tagln", "Myl9", "Ndufa4l2", "Tpm2", 
    "Igfbp7", "Cald1", "Sod3", "Ccl19", "Col18a1", "Sparcl1", 
    "Ccl2", "Myh11", "Lhfp", "Mfge8", "Ppp1r14a", "Rergl", "Igfbp5", 
    "Notch3", "Ptp4a3", "Cpe", "Mcam", "Tinagl1", "Cav1", "Tpm1", 
    "Bgn", "Frzb", "Gja4", "Pdgfrb", "Timp3", "Dstn", "Csrp2", 
    "Map1b", "Mylk", "Cavin3", "Col4a2", "Cox4i2", "Sorbs2", 
    "Sparc", "Higd1b", "Serping1", "Polr2k", "Adamts1", "Pln", 
    "Gpx3", "Timp1", "Id3", "Col4a1", "Thy1", "Ifitm3", "Filip1l", 
    "Pgf", "Cavin1", "A2m", "Crispld2", "Rgs16", "Map3k7cl", 
    "Cryab", "C1qtnf1", "Nr2f2", "Csrp1", "Tppp3", "Isyna1", 
    "Eps8", "Steap4", "Tgfb1i1", "Pcolce", "Lmod1", "Egr1", "Col6a2", 
    "Tsc22d1", "Jag1", "Rasd1", "Flna", "Ntrk2", "Smoc2", "Mef2c", 
    "Epas1", "Mgst3", "Wfdc1", "Ednra", "Oaz2", "Ptk2", "Angptl4", 
    "Serpinf1", "Adamts4", "Myc", "Fhl1", "Dkk3", "Bcam", "Sdc2", 
    "Cnn3", "Cdkn1a", "Synpo2", "Cav2"), `Response to Hypoxia` = c("Alas2", 
    "Ang", "Arnt2", "Bnip3", "Cd24a", "Chrna4", "Chrna7", "Chrnb2", 
    "Cldn3", "Crebbp", "Cxcr4", "Egln1", "Egln2", "Ep300", "Epas1", 
    "Hif1a", "Hsp90b1", "Mt3", "Ciao3", "Nf1", "Pdia2", "Plod1", 
    "Plod2", "Pml", "Smad3", "Smad4", "Tgfb2", "Vegfa"), `Stress Response` = c("Hikeshi", 
    "P4hb", "Uba52", "Mapk1", "Rpa2", "Rpa3", "Tnrc6a", "Tnrc6b", 
    "Tnrc6c", "Nup210", "Rbx1", "Ubb", "Ubc", "Crebbp", "Ets1", 
    "Lamtor1", "Eed", "Lamtor2", "Hsp90aa1", "Rbbp4", "Lamtor4", 
    "Lamtor5", "Psmb10", "Cdkn1a", "Anapc11", "Psma1", "Atg4d", 
    "Psma2", "Wipi2", "Psma3", "Tfdp2", "Psma4", "Atm", "Cycs", 
    "Psma5", "Wdr45", "Anapc16", "Psma6", "Ehmt1", "Psma7", "Ehmt2", 
    "Terf1", "Psmc1", "Atr", "Psmc3", "Sod1", "Psmc4", "Psmc5", 
    "Psmc6", "Psme1", "Atg3", "Ncf1", "Psme2", "Atg5", "Chmp2a", 
    "Chmp2b", "Gsk3b", "Rps19bp1", "Tpr", "Mdm4", "Elob", "Cdc26", 
    "Eloc", "St13", "Rps6ka1", "Eef1a1", "Rps6ka3", "Dnajb1", 
    "Camk2g", "Rps27a", "Txn2", "Prdx1", "Prdx2", "Dnajb6", "Fkbp4", 
    "Prdx3", "Map2k3", "Mtmr14", "Atg12", "Prdx5", "Rheb", "Prdx6", 
    "Gstp1", "Atg14", "Rela", "Gpx1", "Vhl", "Hspa1a", "Ube2d1", 
    "Terf2ip", "Hspa1b", "Ube2d2a", "Txn1", "Ube2d3", "Hsph1", 
    "Cyba", "Cdk4", "Hsf1", "Cdk6", "Mapkapk3", "Cited2", "Map1lc3b", 
    "Psmd12", "Hif1a", "Hmga1", "Psmd13", "Mink1", "Psmd14", 
    "Hsp90ab1", "Ptges3", "Hsbp1", "Nfkb1", "Uvrag", "Cat", "Psmb1", 
    "Cdkn2c", "Psmb2", "Cdkn2d", "Fos", "Psmb3", "Ccs", "Jun", 
    "Gabarapl1", "Gabarapl2", "Psmb6", "Kdm6b", "Psmb8", "Psmd2", 
    "Tnik", "Psmb9", "Psmd3", "Ranbp2", "Atox1", "Sem1", "Psmd6", 
    "Gabarap", "Psmd7", "Psmf1", "Chmp3", "Stat3", "Psmd8", "Tinf2", 
    "Psmd9", "Chmp7", "Ccar2", "Hspa4", "Ywhae", "Bag1", "Hspa5", 
    "Bag3", "Dynll1", "Hspa8", "Rb1cc1", "Bag5", "Anapc5", "Dynll2", 
    "Vcp", "Dnajc2", "Cabin1", "Cebpb"), `T activation` = c("Cd3e", 
    "Cd69", "Cd38"), `T Naïve` = c("Lef1", "Ccr7", "Tcf7"), 
    `Transitional B` = c("Mme", "Cd38", "Cd24a", "Acsm3", "Msi2"
    ),`infCNV prediction` = c("proportion-cnv-chr1", "proportion-cnv-chr2", 
                                                                     "proportion-cnv-chr3", "proportion-cnv-chr4", "proportion-cnv-chr5", 
                                                                     "proportion-cnv-chr6", "proportion-cnv-chr7", "proportion-cnv-chr8", 
                                                                     "proportion-cnv-chr9", "proportion-cnv-chr10", "proportion-cnv-chr11", 
                                                                     "proportion-cnv-chr12", "proportion-cnv-chr13", "proportion-cnv-chr14", 
                                                                     "proportion-cnv-chr15", "proportion-cnv-chr16", "proportion-cnv-chr17", 
                                                                     "proportion-cnv-chr18"))


```



```{r Load libraries and files, message=FALSE, warning=FALSE, paged.print=FALSE}
library(easypackages)
MyPackages<-c("dplyr","ggplot2","ggpubr","gridExtra","viridis","egg","presto","ComplexHeatmap",
              "Seurat","cowplot","patchwork","stringr", "ggmin","SingleCellExperiment","CellChat")
libraries(MyPackages)


SeuratObj=readRDS(paste0(RobjDirectory,"SantoshAllClustersnew.rds"))
SeuratObjT=readRDS(paste0(RobjDirectory,"TandNKcellsonlyNew.rds"))


##color palettes needed
SampleColors=c(Ctrl = "#003F5C", KO_1 = "#E46388", KO_3 = "#8DB032")
ClusterColors=c(C01 = "#8DB032", C02 = "#61AA4F", C03 = "#60AD62", C04 = "#C9C759", 
                C05 = "#F8C238", C06 = "#FEA905", C07 = "#FF9022", C08 = "#FB7B3E", 
                C09 = "#E97B25", C10 = "#E6722E", C11 = "#F5615E", C12 = "#DE4F56", 
                C13 = "#BE3F40", C14 = "#DF606C", C15 = "#EE6E88", C16 = "#DA5787", 
                C17 = "#D8629C", C18 = "#DF80BE", C19 = "#BC66A8", C20 = "#9F559B", 
                C21 = "#9E68B9", C22 = "#8C67B6", C23 = "#6B5496", C24 = "#4566B1", 
                C25 = "#227ACD", C26 = "#2A5C9A", C27 = "#235982", C28 = "#087C91", 
                C29 = "#00697E", C30 = "#003F5C")
AssignmentColors=c(BCells = "#003F5C", Blood = "#0A7A90", CAFs = "#2960A1", DCs = "#4D61A8", 
                   Epithelial = "#956CBF", Macs = "#A45498", Mastcells = "#DC73B0", 
                   Monocytes = "#E46388", Myeloid_Prog = "#CD4E53", Neutrophils = "#F45A66", 
                   NKcells = "#E47B1E", Plasmablast = "#FF8B2B", Tcells = "#F9BF31", 
                   Tumor = "#68AF61", Vasc = "#8DB032")
TAssignmentColors=c(`Activated TCells` = "#003F5C", `CD4+ TCells` = "#205D83", 
`CD8+ TCells` = "#3D6BB9", doublet = "#9E6DC1", `Effector CD4+ TCells` = "#D378B8", 
`Effector Memory` = "#E46388", `Exhasted CD8+ TCells` = "#C94446", 
`Naiive TCells-CD8+` = "#E27820", NKcells = "#FF951A", `Proliferating TCells` = "#BFC45A", 
Treg = "#8DB032")

```
Supplementary Figure 4a

```{r Supplementary Figure 4a , eval=FALSE}
#please refer to the output of infercnv::run 
plot_cnv(infercnv_object,
         out_dir=OutputDirectory
         )

```

Supplementary Figure 5a

```{r Supplementary Figure 5a, fig.height=12, fig.width=18, message=FALSE, warning=FALSE, paged.print=FALSE}
#please refer to the output of infercnv::run 
#mapmeta=read.delim(file = paste0("./infercnv/map_metadata_from_infercnv.txt"))
SeuratObj=AddMetaData(SeuratObj,mapmeta)
P1=DotPlot(SeuratObj,group.by = "Assignment",features = c("proportion_cnv_chr1", "proportion_cnv_chr2", "proportion_cnv_chr3", 
                                                       "proportion_cnv_chr4", "proportion_cnv_chr5", "proportion_cnv_chr6", 
                                                       "proportion_cnv_chr7", "proportion_cnv_chr8", "proportion_cnv_chr9", 
                                                       "proportion_cnv_chr10", "proportion_cnv_chr11", "proportion_cnv_chr12", 
                                                       "proportion_cnv_chr13", "proportion_cnv_chr14", "proportion_cnv_chr15", 
                                                       "proportion_cnv_chr16", "proportion_cnv_chr17", "proportion_cnv_chr18", 
                                                       "proportion_cnv_chr19"),col.min = 0,scale = T#,scale.by = "size"
)+RotatedAxis() +scale_colour_viridis_c(option = "plasma")+ggtitle("infCNV predictions")+
  DotPlot(SeuratObj,group.by = "Cluster",features = c("proportion_cnv_chr1", "proportion_cnv_chr2", "proportion_cnv_chr3", 
                                                   "proportion_cnv_chr4", "proportion_cnv_chr5", "proportion_cnv_chr6", 
                                                   "proportion_cnv_chr7", "proportion_cnv_chr8", "proportion_cnv_chr9", 
                                                   "proportion_cnv_chr10", "proportion_cnv_chr11", "proportion_cnv_chr12", 
                                                   "proportion_cnv_chr13", "proportion_cnv_chr14", "proportion_cnv_chr15", 
                                                   "proportion_cnv_chr16", "proportion_cnv_chr17", "proportion_cnv_chr18", 
                                                   "proportion_cnv_chr19"),col.min = 0)+RotatedAxis() +scale_colour_viridis_c(option = "plasma") 
P1[[1]][["guides"]][["guides"]][["colour"]][["params"]][["title"]]="CNV Proportion"
P1[[2]][["guides"]][["guides"]][["colour"]][["params"]][["title"]]="CNV Proportion"
P1[[1]][["guides"]][["guides"]][["size"]][["params"]][["title"]]="Percent of cells"
P1[[2]][["guides"]][["guides"]][["size"]][["params"]][["title"]]="Percent of cells"

P2=DotPlot(SeuratObj,group.by = "Assignment",features = c("Pcm1","Map1b","Hspg2","Serpine1","Scd2","Nrp2","Nedd4",
                                                       "Tead1","Eprs","Hspa9","Myc","Ubr4","Prrc2a","Flnb","Tcf20"),col.min = 0.5,scale.min = 10)+ggtitle("E0771 Markers")+RotatedAxis() +scale_colour_viridis_c(option = "plasma") +
  DotPlot(SeuratObj,group.by = "Cluster",features = c("Pcm1","Map1b","Hspg2","Serpine1","Scd2","Nrp2","Nedd4","Tead1","Eprs","Hspa9","Myc","Ubr4","Prrc2a","Flnb","Tcf20"),col.min = 0)+RotatedAxis() +scale_colour_viridis_c(option = "plasma") ;P1/P2

pdf(paste0(OutputDirectory,"Supplementary Figure 5a.pdf"),height=12,width=18)
P1/P2
dev.off()


```


Supplementary Figure 5b

```{r Supplementary Figure 5b, fig.height=5, fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
infCNVassay=CreateAssayObject(t(mapmeta[,-1]))
SeuratObj@assays[["infCNV"]]=infCNVassay
SeuratObj <-  AddModuleScore(SeuratObj,assay = "infCNV",slot = "counts",nbin = 20,
                             features = list(`infCNV prediction` = c("proportion-cnv-chr1", "proportion-cnv-chr2", 
                                                                     "proportion-cnv-chr3", "proportion-cnv-chr4", "proportion-cnv-chr5", 
                                                                     "proportion-cnv-chr6", "proportion-cnv-chr7", "proportion-cnv-chr8", 
                                                                     "proportion-cnv-chr9", "proportion-cnv-chr10", "proportion-cnv-chr11", 
                                                                     "proportion-cnv-chr12", "proportion-cnv-chr13", "proportion-cnv-chr14", 
                                                                     "proportion-cnv-chr15", "proportion-cnv-chr16", "proportion-cnv-chr17", 
                                                                     "proportion-cnv-chr18")),
                             ctrl = 1,
                             name = "infCNVScore")
colnames(SeuratObj@meta.data)[colnames(SeuratObj@meta.data)=="infCNVScore1"]="infCNVMetaScore"

q=quantile(SeuratObj$infCNVMetaScore,probs=0.9)
SeuratObj@meta.data=SeuratObj@meta.data%>%mutate(CNV_Prediction=ifelse(infCNVMetaScore>q,"Malignant","Normal"))
p=DimPlot(SeuratObj,group.by = "CNV_Prediction",label = T,order = "Malignant")+DimPlot(SeuratObj,group.by = "Assignment",label = T,cols=AssignmentColors)&ggmin::theme_min();p
pdf(paste0(OutputDirectory,"Supplementary Figure 5b.pdf"),height=5,width=10)
print(p)

dev.off()


```


Supplementary Figure 6a

```{r Supplementary Figure 6a, fig.height=4, fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
markers <- wilcoxauc(SeuratObj , 'Cluster',assay = "scale.data")
markers=markers[order(markers$group),]

top2 <- markers %>% group_by(group) %>% top_n(n =2, wt = logFC)
top2=top2[order(top2$group),]
genes= top2$feature

p=DotPlot(SeuratObj,group.by = "Cluster",dot.scale = 5 ,features = unique(genes) ,scale = T)+scale_colour_viridis_c(option = "plasma")+
  ggmin::theme_min()+ RotatedAxis()+theme(axis.title = element_blank());p

pdf(paste0(OutputDirectory,"Supplementary Figure 6a.pdf"),width=10,height=4)
print(p)
dev.off()

```
Supplementary Figure 6b

```{r Supplementary Figure 6b, fig.height=12, fig.width=20, message=FALSE, warning=FALSE, paged.print=FALSE}
#refer to preprocessing for module scoring using seurat:: AddModuleScore of these signatures
TandNKcells <-c("NK", 
                "CD4+ T activated", "CD4+ T Naïve", 
                "CD8+ T", "T activation", "T Naïve","Naïve"
)
Bcells <- c("Naïve CD20+ B", "B1 B", "Transitional B")
Blood <- c("Normoblast", "Erythroblast"#, "Proerythroblast"
)
Proganitor= c("Lymph prog","G/M prog",#"HSC",
              "MK/E prog","ID2-hi myeloid prog")
plasma= c("Plasma cells", "Plasmablast")
Monocytes <- c( "CD14+ Mono", "CD16+ Mono")
OtherMyeloid =c("Mast","Basophil", "Neutrophils")
Fibroblasts=c("Fibroblasts",#"Keratinocytes",
              "CAFs")
DCs <- c( "pDCs","cDC1", "cDC2", "cDC3")
Macrophages <- c( "Macs","M2_Macs")
Metabolism <- c("Oxidative phosphorylation", "Glycolysis", "Fatty acid metabolism")
Apoptosis <- c("Pro_Apoptosis", "Anti_Apoptosis")
Tumor <-c("E0771 markers","infCNVMetaScore")
Stroma <- c("Normal Epithelial","Endothelial","PVL")
HypoxiaAndStress <- c("Response to Hypoxia","Hypoxia","Stress Response")


MarkerNameVector <- c(TandNKcells, Bcells,Blood, Proganitor,plasma,Monocytes,DCs,Macrophages,OtherMyeloid,
                      Fibroblasts,Stroma,Tumor,Metabolism, Apoptosis,HypoxiaAndStress)
FunctionScoreMatrix <- matrix(0,
                              ncol = length(unique(SeuratObj$Cluster)),
                              nrow = length(marker.list))
colnames(FunctionScoreMatrix) <- levels(as.factor(SeuratObj$Cluster))
rownames(FunctionScoreMatrix) <- MarkerNameVector
library(scales)
SeuratObj$Cluster=factor(SeuratObj$Cluster)
for(ci in 1:ncol(FunctionScoreMatrix)){
  for(ri in 1:nrow(FunctionScoreMatrix)){
    FunctionVec <- as_tibble(SeuratObj@meta.data) %>% pull(MarkerNameVector[ri])
    fv <- mean(FunctionVec[SeuratObj$Cluster == levels(SeuratObj$Cluster)[ci]])
    FunctionScoreMatrix[ri, ci] <- fv
  }
}
FunctionScoreMatrix <- t(apply(FunctionScoreMatrix, 1, rescale	, to=c(-1, 1)))


signatureType_row <- data.frame(Signature.type = c(
  rep("TandNKcells", length(TandNKcells)),
  rep("Bcells", length(Bcells)),
  rep("Blood", length(Blood)),
  rep("Proganitor", length(Proganitor)),  rep("plasma", length(plasma)),
  rep("Monocytes", length(Monocytes)),  rep("DCs", length(DCs)),
  rep("Macrophages", length(Macrophages)),  rep("OtherMyeloid", length(OtherMyeloid)),
  rep("Fibroblasts", length(Fibroblasts)), rep("Stroma", length(Stroma)), rep("Tumor", length(Tumor)),
  rep("Metabolism", length(Metabolism)),
  rep("Apoptosis", length(Apoptosis)),rep("HypoxiaAndStress", length(HypoxiaAndStress))))
rownames(signatureType_row) <- MarkerNameVector
signatureType_row$Signature.type=factor(signatureType_row$Signature.type,levels =unique(signatureType_row$Signature.type) )
frq=as.data.frame(table(signatureType_row))

RowColors= c("#003F5C", "#0A7A90", "#2960A1", "#4D61A8", "#956CBF", "#A45498", 
"#DC73B0", "#E46388", "#CD4E53", "#F45A66", "#E47B1E", "#FF8B2B", 
"#F9BF31", "#68AF61", "#8DB032")
names(RowColors)= levels(as.factor(signatureType_row$Signature.type))
Rcol=list('Signature.type'=RowColors)
rowanno <- rowAnnotation(df=signatureType_row,
                         show_annotation_name =F,show_legend = T,col=Rcol)
col<- circlize::colorRamp2(breaks = c(-1, 0, 1), colors = c("#007dd1", "white", "#ab3000"))

H1=Heatmap(name = "ModuleScore",FunctionScoreMatrix,right_annotation =rowanno,row_split = signatureType_row$Signature.type,
           column_km = 10,
           cluster_rows = F ,col = col,show_column_dend = T,row_title_rot = 0,
           row_title_side = "left",border = "black")


FunctionScoreMatrix2 <- matrix(0,
                               ncol = length(unique(SeuratObj$Assignment)),
                               nrow = length(marker.list))
colnames(FunctionScoreMatrix2) <- levels(as.factor(SeuratObj$Assignment))
rownames(FunctionScoreMatrix2) <- MarkerNameVector
library(scales)
SeuratObj$Assignment=factor(SeuratObj$Assignment)
for(ci in 1:ncol(FunctionScoreMatrix2)){
  for(ri in 1:nrow(FunctionScoreMatrix2)){
    FunctionVec <- as_tibble(SeuratObj@meta.data) %>% pull(MarkerNameVector[ri])
    fv <- mean(FunctionVec[SeuratObj$Assignment == levels(SeuratObj$Assignment)[ci]])
    FunctionScoreMatrix2[ri, ci] <- fv
  }
}
FunctionScoreMatrix2 <- t(apply(FunctionScoreMatrix2, 1, rescale	, to=c(-1, 1)))
H2=Heatmap(name = "ModuleScore",FunctionScoreMatrix2,right_annotation =rowanno,row_split = signatureType_row$Signature.type,
           column_km = 9,
           cluster_rows = F ,col = col,show_column_dend = T,row_title_rot = 0,
           row_title_side = "left",border = "black")
H1+H2
pdf(paste0(OutputDirectory,"Supplementary Figure 6b.pdf"),width = 20,height =12)
H1+H2
dev.off()

```


Supplementary Figure 7b

```{r Supplementary Figure 7b, fig.height=4, fig.width=8, message=FALSE, warning=FALSE, paged.print=FALSE}
Immune=c("Fasl","Klrk1",#"Hcst",
         "Tnfsf10","Cd8b1")
Tumor=c("Fas","Ulbp1","Tnfrsf10b","H2-D1")

Idents(SeuratObj)=SeuratObj$Assignment
p1=DotPlot(SeuratObj,group.by = "Sample",idents="Tumor",dot.scale = 5 ,features = Tumor ,scale = T)+
  scale_colour_viridis_c(option = "plasma")+
  ggmin::theme_min()+ RotatedAxis()+theme(axis.title = element_blank())+
  labs(title=paste("Tumor"))+coord_flip()+NoLegend()

p2=DotPlot(SeuratObj,group.by = "Sample",idents="Tcells",dot.scale = 5 ,features = Immune ,scale = T)+
  scale_colour_viridis_c(option = "plasma")+
  ggmin::theme_min()+ RotatedAxis()+theme(axis.title = element_blank())+
  labs(title=paste("Tcells"))+coord_flip()+NoLegend()

p3=DotPlot(SeuratObj,group.by = "Sample",idents="NKcells",dot.scale = 5 ,features = Immune ,scale = T)+
  scale_colour_viridis_c(option = "plasma")+
  ggmin::theme_min()+ RotatedAxis()+theme(axis.title = element_blank())+
  labs(title=paste("NKcells"))+coord_flip();p1+p2+p3

pdf(paste0(OutputDirectory,"Supplementary Figure 7b.pdf"),width=8,height=4)
p1+p2+p3
dev.off()

```